name: develop test

on: 
    push:
        branches:
            - develop

jobs:
    test:
        name: Simple run test
        runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
    uses: actions/setup-python@v1
    with:
        python-version: 3.8
    
    - name: Install dependencies
    run: |
        python -m pip install --upgrade pip
        pip install . --user --upgrade
        pip install argparse son sys datetime elasticsearch
    
    - name: Test with local PAS_instance
    run: |
        python3.8 PAS_builder.py \
            --pipeline=local_PAS_instance \
            --OT_input=local_PAS_instance
